#lang racket
(define y
  '(lambda (h)
     ((lambda (f) (f f))
      (lambda (g)
        (h (lambda (x) ((g g) x)))))))
(define interp
  `(,y (lambda (interp)
         (lambda (exp)
           (lambda (env)
             (lambda (k)
               (cond
                 ((number? exp) (k exp))
                 ((boolean? exp) (k exp))
                 ((symbol? exp) (k (env exp)))
                 ((eq? (car exp) 'cond)
                  ((,y (lambda (loop)
                         (lambda (cls)
                           (((interp (car (car cls))) env)
                            (lambda (bool)
                              (if bool
                                  (((interp (car (cdr (car cls)))) env) k)
                                  (loop (cdr cls)))))))) (cdr exp)))
                 ((eq? (car exp) 'quote) (k (car (cdr exp))))
                 ((eq? (car exp) 'eq?)
                  (((interp (car (cdr exp))) env)
                   (lambda (v1)
                     (((interp (car (cdr (cdr exp)))) env)
                      (lambda (v2) (k (eq? v1 v2)))))))
                 ((eq? (car exp) '=)
                  (((interp (car (cdr exp))) env)
                   (lambda (v1)
                     (((interp (car (cdr (cdr exp)))) env)
                      (lambda (v2) (k (= v1 v2)))))))
                 ((eq? (car exp) '*)
                  (((interp (car (cdr exp))) env)
                   (lambda (v1)
                     (((interp (car (cdr (cdr exp)))) env)
                      (lambda (v2) (k (* v1 v2)))))))
                 ((eq? (car exp) 'cons)
                  (((interp (car (cdr exp))) env)
                   (lambda (v1)
                     (((interp (car (cdr (cdr exp)))) env)
                      (lambda (v2) (k (cons v1 v2)))))))
                 ((eq? (car exp) 'number?)
                  (((interp (car (cdr exp))) env)
                   (lambda (n) (k (number? n)))))
                 ((eq? (car exp) 'boolean?)
                  (((interp (car (cdr exp))) env)
                   (lambda (b) (k (boolean? b)))))
                 ((eq? (car exp) 'symbol?)
                  (((interp (car (cdr exp))) env)
                   (lambda (s) (k (symbol? s)))))
                 ((eq? (car exp) 'zero?)
                  (((interp (car (cdr exp))) env)
                   (lambda (n) (k (zero? n)))))
                 ((eq? (car exp) 'sub1)
                  (((interp (car (cdr exp))) env)
                   (lambda (n) (k (sub1 n)))))
                 ((eq? (car exp) 'null?)
                  (((interp (car (cdr exp))) env)
                   (lambda (l) (k (null? l)))))
                 ((eq? (car exp) 'car)
                  (((interp (car (cdr exp))) env)
                   (lambda (p) (k (car p)))))
                 ((eq? (car exp) 'cdr)
                  (((interp (car (cdr exp))) env)
                   (lambda (p) (k (cdr p)))))
                 ((eq? (car exp) 'if)
                  (((interp (car (cdr exp))) env)
                   (lambda (bool)
                     (if bool
                         (((interp (car (cdr (cdr exp)))) env) k)
                         (((interp (car (cdr (cdr (cdr exp))))) env) k)))))
                 ((eq? (car exp) 'lambda)
                  (k (lambda (arg)
                       (lambda (k)
                         (((interp (car (cdr (cdr exp))))
                           (lambda (var)
                             (if (eq? (car (car (cdr exp))) var)
                                 arg
                                 (env var)))) k)))))
                 (#t
                  (((interp (car exp)) env)
                   (lambda (rator)
                     (((interp (car (cdr exp))) env)
                      (lambda (rand)
                        ((rator rand) k)))))))))))))