#lang racket
(provide convert)
(require "match.rkt")
(define (convert-attrs attrs)
  (for-each
   (lambda (attr)
     (printf " ~s=~s" (car attr) (cadr attr)))
   attrs))
(define (convert exp)
  (match exp
    ((,tag) (printf "<~s/>" tag))
    ((,tag ,attrs)
     (guard (pair? attrs) (pair? (car attrs)))
     (printf "<~s" tag)
     (convert-attrs attrs)
     (printf ">"))
    ((,tag ,attrs . ,exps)
     (guard (pair? attrs) (pair? (car attrs)))
     (printf "<~s" tag)
     (convert-attrs attrs)
     (printf ">")
     (for-each convert exps)
     (printf "</~s>" tag))
    ((,tag . ,exps)
     (printf "<~s>" tag)
     (for-each convert exps)
     (printf "</~s>" tag))
    (else
     (printf "~a" exp))))